name = "DeerCraft"
author = "ceski23"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a579894b2efad8aa655c82383190ce93980d66ace0bf9f37b955c69558a414c"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
