name = "DeerCraft"
author = "ceski23"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "987b69e36a7c47cb57e816bfcd2a275e8f642c0935af30f55081ea3f81e63249"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
