name = "DeerCraft"
author = "ceski23"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8401a6a1f791559dcbb50cacec79175b2388df1797a8e04e63e383fcc1df9d40"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
